# Generated by Django 5.0 on 2025-01-13 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('climate', models.CharField(blank=True, max_length=128, null=True)),
                ('diameter', models.IntegerField(blank=True, null=True)),
                ('orbital_period', models.IntegerField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('rotation_period', models.IntegerField(blank=True, null=True)),
                ('surface_water', models.FloatField(blank=True, null=True)),
                ('terrain', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Planet (ex09)',
                'verbose_name_plural': 'Planets (ex09)',
                'db_table': 'ex09_planets',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('birth_year', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, max_length=32, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=32, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=32, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('homeworld', models.ForeignKey(blank=True, db_column='homeworld', null=True, on_delete=django.db.models.deletion.CASCADE, to='ex09.planets', to_field='name')),
            ],
            options={
                'verbose_name': 'Person (ex09)',
                'verbose_name_plural': 'People (ex09)',
                'db_table': 'ex09_people',
            },
        ),
    ]
