# Generated by Django 5.0 on 2025-01-13 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(blank=True, db_column='homeworld', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ex09.planets', to_field='name'),
        ),
    ]
