# Generated by Django 5.0 on 2025-01-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ex08Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('climate', models.CharField(blank=True, max_length=128, null=True)),
                ('diameter', models.IntegerField(blank=True, null=True)),
                ('orbital_period', models.IntegerField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('rotation_period', models.IntegerField(blank=True, null=True)),
                ('surface_water', models.FloatField(blank=True, null=True)),
                ('terrain', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Planet (ex08)',
                'verbose_name_plural': 'Planets (ex08)',
                'db_table': 'ex08_planets',
            },
        ),
        migrations.CreateModel(
            name='Ex08People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('birth_year', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, max_length=32, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=32, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=32, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('homeworld', models.ForeignKey(db_column='homeworld', on_delete=django.db.models.deletion.CASCADE, to='ex08.ex08planets', to_field='name')),
            ],
            options={
                'verbose_name': 'Person (ex08)',
                'verbose_name_plural': 'People (ex08)',
                'db_table': 'ex08_people',
            },
        ),
    ]
