# Generated by Django 5.0 on 2025-01-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(blank=True, db_column='homeworld', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ex10.planets'),
        ),
    ]
